// account action types
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const GET_ACCOUNT_TYPES = "GET_ACCOUNT_TYPES";
export const SET_ACCOUNT_TYPES = "SET_ACCOUNT_TYPES";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
export const SET_SELECTED_ACCOUNTS = "SET_SELECTED_ACCOUNTS";
export const SAVE_ACCOUNT = "SAVE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DEACTIVATE_ACCOUNT = "DEACTIVATE_ACCOUNT";

// api status actions
export const SET_API_ERROR = "SET_API_ERROR";
export const CLEAR_API_ERROR = "CLEAR_API_ERROR";

// bank statement action types
export const GET_BANK_STATEMENTS = "GET_BANK_STATEMENTS";
export const SET_BANK_STATEMENTS = "SET_BANK_STATEMENTS";
export const CONFIRM_DELETE_BANK_STATEMENT = "CONFIRM_DELETE_BANK_STATEMENT";
export const CANCEL_DELETE_BANK_STATEMENT = "CANCEL_DELETE_BANK_STATEMENT";
export const DELETE_BANK_STATEMENT = "DELETE_BANK_STATEMENT";

// budget action types
export const GET_BUDGETS = "GET_BUDGETS";
export const SET_BUDGETS = "SET_BUDGETS";
export const SAVE_BUDGET = "SAVE_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";

// category action types
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORY_TYPES = "SET_CATEGORY_TYPES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_SUBCATEGORIES = "SET_SUBCATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const SET_CURRENT_SUBCATEGORY = "SET_CURRENT_SUBCATEGORY";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SAVE_SUBCATEGORY = "SAVE_SUBCATEGORY";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const SET_CATEGORY = "SET_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";
export const REMOVE_SUBCATEGORY = "REMOVE_SUBCATEGORY";

// date range action types
export const GET_DATE_RANGES = "GET_DATE_RANGES";
export const SET_DATE_RANGES = "SET_DATE_RANGES";
export const SET_CURRENT_DATE_RANGE = "SET_CURRENT_DATE_RANGE";
export const UPDATE_CURRENT_DATE_RANGE = "UPDATE_CURRENT_DATE_RANGE";

export const SOURCE_CATEGORY_REPORT = "SOURCE_CATEGORY_REPORT";
export const SOURCE_SUBCATEGORY_REPORT = "SOURCE_SUBCATEGORY_REPORT";

// form action types
export const SHOW_FORM_MODAL = "formStore/showFormModal";
export const HIDE_FORM_MODAL = "formStore/hideFormModal";

// import action types
export const UPLOAD_OFX = "UPLOAD_OFX";
export const SET_OFX_TRANSACTIONS = "SET_OFX_TRANSACTIONS";
export const SAVE_TRANSACTIONS = "SAVE_TRANSACTIONS";
export const SET_NOTES = "SET_NOTES";
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";
export const SET_SUBCATEGORY_ID = "SET_SUBCATEGORY_ID";
export const SET_IMPORT = "SET_IMPORT";

// loan action types
export const SET_LOAN_REPORT = "SET_LOAN_REPORT";
export const SET_LOAN_VIEW = "SET_LOAN_VIEW";

// matching transaction action types
export const GET_MATCHING_TRANSACTIONS = "GET_MATCHING_TRANSACTIONS";
export const SET_MATCHING_TRANSACTIONS = "SET_MATCHING_TRANSACTIONS";

// pattern action types
export const GET_PATTERNS = "GET_PATTERNS";
export const SET_PATTERNS = "SET_PATTERNS";
export const SAVE_PATTERN = "SAVE_PATTERN";
export const DELETE_PATTERN = "DELETE_PATTERN";

// reconciliation action types
export const GET_RECONCILIATIONS = "GET_RECONCILIATIONS";
export const SET_RECONCILIATIONS = "SET_RECONCILIATIONS";
export const SAVE_RECONCILIATION = "SAVE_RECONCILIATION";

// report action types
export const GET_REPORT = "GET_REPORT";
export const SET_ACCOUNT_BALANCE_REPORT = "SET_ACCOUNT_BALANCE_REPORT";
export const TOGGLE_REPORT_VIEW = "TOGGLE_REPORT_VIEW";
export const SET_TRANSACTION_REPORT = "SET_TRANSACTION_REPORT";
export const SET_TOTALS_REPORT = "SET_TOTALS_REPORT";
export const SET_INCOME_VS_EXPENSE = "SET_INCOME_VS_EXPENSE";

// transaction action types
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SAVE_TRANSACTION = "SAVE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_SEARCH_DESCRIPTION = "SET_SEARCH_DESCRIPTION";
export const TOGGLE_MORE_OR_LESS = "TOGGLE_MORE_OR_LESS";
