require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "spec/features/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

FactoryBot/SyntaxMethods:
  Enabled: false
