require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - "config.ru"
    - "api/**/*"
    - "node_modules/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "spec/lib/**/*"
    - "spec/javascripts/**/*"
    - "spec/features/**/*"
    - "config/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "web/**/*"

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

MethodLength:
  Max: 15

LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

ClassLength:
  Max: 120

RSpec/MultipleExpectations:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
