# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f650685d60b196aed028c932a3f016e2dbe95aca8721f0a3bed2619469dcadae0662278cbce1c68aeaf1246ed2af16911e393d110ec72f24a2b0c076459eea79

test:
  secret_key_base: d2124686509b510cb7be3e1d6307aaeca60d32d2ebcc73c31aff1c9a1da6fd2ae75fab8541f7a0ef622ec56e41994b0133c69987858d75a2411877598d4dd11f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
