require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReconciliationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Reconciliation. As you add validations to Reconciliation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {account_id: 1, statement_date: "2014-07-01", statement_balance: 9.99}
  }

  let(:invalid_attributes) {
    {account_id: -1, statement_date: "blah", statement_balance: "blah"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReconciliationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reconciliations as @reconciliations" do
      reconciliation = Reconciliation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:reconciliations)).to eq([reconciliation])
    end
  end

  describe "GET show" do
    it "assigns the requested reconciliation as @reconciliation" do
      reconciliation = Reconciliation.create! valid_attributes
      get :show, {:id => reconciliation.to_param}, valid_session
      expect(assigns(:reconciliation)).to eq(reconciliation)
    end
  end

  describe "GET new" do
    it "assigns a new reconciliation as @reconciliation" do
      get :new, {}, valid_session
      expect(assigns(:reconciliation)).to be_a_new(Reconciliation)
    end
  end

  describe "GET edit" do
    it "assigns the requested reconciliation as @reconciliation" do
      reconciliation = Reconciliation.create! valid_attributes
      get :edit, {:id => reconciliation.to_param}, valid_session
      expect(assigns(:reconciliation)).to eq(reconciliation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reconciliation" do
        expect {
          post :create, {:reconciliation => valid_attributes}, valid_session
        }.to change(Reconciliation, :count).by(1)
      end

      it "assigns a newly created reconciliation as @reconciliation" do
        post :create, {:reconciliation => valid_attributes}, valid_session
        expect(assigns(:reconciliation)).to be_a(Reconciliation)
        expect(assigns(:reconciliation)).to be_persisted
      end

      it "redirects to the transaction reconciliation list" do
        post :create, {:reconciliation => valid_attributes}, valid_session
        expect(response).to redirect_to(reconciliations_transactions_path(assigns(:reconciliation)))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reconciliation as @reconciliation" do
        post :create, {:reconciliation => invalid_attributes}, valid_session
        expect(assigns(:reconciliation)).to be_a_new(Reconciliation)
      end

      it "re-renders the 'new' template" do
        post :create, {:reconciliation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
    	{account_id: 2, statement_date: "2014-07-02", statement_balance: 9.77, reconciled: true}
      }

      it "updates the requested reconciliation" do
        reconciliation = Reconciliation.create! valid_attributes
        put :update, {:id => reconciliation.to_param, :reconciliation => new_attributes}, valid_session
        reconciliation.reload
        expect(reconciliation.account_id).to eq(2)
        expect(reconciliation.statement_date).to eq(Date.new(2014, 07, 02))
        expect(reconciliation.statement_balance).to eq(9.77)
        expect(reconciliation.reconciled).to be_truthy
      end

      it "assigns the requested reconciliation as @reconciliation" do
        reconciliation = Reconciliation.create! valid_attributes
        put :update, {:id => reconciliation.to_param, :reconciliation => valid_attributes}, valid_session
        expect(assigns(:reconciliation)).to eq(reconciliation)
      end

      it "redirects to the reconciliation" do
        reconciliation = Reconciliation.create! valid_attributes
        put :update, {:id => reconciliation.to_param, :reconciliation => valid_attributes}, valid_session
        expect(response).to redirect_to(reconciliation)
      end
    end

    describe "with invalid params" do
      it "assigns the reconciliation as @reconciliation" do
        reconciliation = Reconciliation.create! valid_attributes
        put :update, {:id => reconciliation.to_param, :reconciliation => invalid_attributes}, valid_session
        expect(assigns(:reconciliation)).to eq(reconciliation)
      end

      it "re-renders the 'edit' template" do
        reconciliation = Reconciliation.create! valid_attributes
        put :update, {:id => reconciliation.to_param, :reconciliation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reconciliation" do
      reconciliation = Reconciliation.create! valid_attributes
      expect {
        delete :destroy, {:id => reconciliation.to_param}, valid_session
      }.to change(Reconciliation, :count).by(-1)
    end

    it "redirects to the reconciliations list" do
      reconciliation = Reconciliation.create! valid_attributes
      delete :destroy, {:id => reconciliation.to_param}, valid_session
      expect(response).to redirect_to(reconciliations_url)
    end
  end

  describe "transactions" do

    it "assigns a list of transactions as @transactions" do
      reconciliation = Reconciliation.create! valid_attributes
      get :transactions, {:id => reconciliation.to_param}, valid_session
      expect(assigns(:reconciliation)).to eq(reconciliation)
      expect(assigns(:transactions)).to be_a(Array)
    end

  end

end
