source 'http://rubygems.org'

gem 'roda'

gem 'sequel'
gem 'sqlite3'
gem 'ruby-enum'
gem 'rack-unreloader'

group :development, :test do
  gem 'rubocop', require: false
  gem 'rspec'
  gem 'rack-test'
end
