name: javascript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - run: yarn
      - run: yarn test

  test-without-components:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - run: yarn
      - run: yarn test:without-components
